webapp/motando/account/urls.py
#
# account/urls.py
#

from django.urls import path
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'account'

urlpatterns = [
    path('login', views.user_login, name='login'),
    path('logout', login_required(views.user_logout), name='logout'),

    path('registro', TemplateView.as_view(template_name='account/choices.html'), name='choices'),
    path('new/user', views.NewUserView.as_view(), name='new_user'),
    path('new/user/success', TemplateView.as_view(template_name='account/confirmation.html'), 
         name='new_user_success'),

    path('user/home', login_required(views.UserProfileHomeView.as_view()), name='home'),
    path('user/profile', login_required(views.UserProfileView.as_view()), name='profile'),
    path('user/password_and_security', login_required(views.UserPasswordSecurityView.as_view()), name='password_security'),
]

webapp/motando/chat/urls.py
#
# chat/urls.py
#

from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'chat'

urlpatterns = [    
    path('home', login_required(views.ChatHomeView.as_view()), name='home'),    
]

webapp/motando/motando/urls.py
from django.urls import path, include

urlpatterns = [
    # Admin Site
    path('motandoadm/', include('motandoadm.urls', namespace='motandoadm')),

    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
    path('classifiedad/', include('classifiedad.urls', namespace='classifiedad')),
    path('chat/', include('chat.urls', namespace='chat')),   

    # API
    path('api/brazil/', include('state_city.api.urls', namespace='api_state_city')),
    path('api/motorcycles/', include('motorcycle.api.urls', namespace='api_motorcycle')),
    path('api/classifiedads/', include('classifiedad.api.urls', namespace='api_classifiedad')),
    path('api/chats/', include('chat.api.urls', namespace='api_chat')),
]

webapp/motando/motandoadm/urls.py
#
# motandoadm/urls.py
#

from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'motandoadm'

urlpatterns = [    
    path('home', login_required(views.HomeAdminView.as_view()), name='home'),  
    
    path('moto', login_required(views.ListAllMotorcycleAdminView.as_view()), name='motorcycle_all_list'),  

    path('moto/marca', login_required(views.ListMotorcycleBrandAdminView.as_view()), name='motorcycle_brand_list'),  
    path('moto/marca/novo', login_required(views.AddMotorcycleBrandAdminView.as_view()), name='motorcycle_brand_add'),  
    path('moto/marca/<int:brand_id>', login_required(views.EditMotorcycleBrandAdminView.as_view()), name='motorcycle_brand_edit'),  
    path('moto/marca/remover/<int:brand_id>', login_required(views.DeleteMotorcycleBrandAdminView.as_view()), name='motorcycle_brand_delete'),  

    path('moto/marca/modelo', login_required(views.SelectMotorcycleBrandModelAdminView.as_view()), name='motorcycle_brand_model_select'),  
    path('moto/marca/modelo/novo', login_required(views.AddMotorcycleBrandModelAdminView.as_view()), name='motorcycle_brand_model_add'),     
    path('moto/marca/<int:brand_id>/modelo', login_required(views.ListMotorcycleBrandModelAdminView.as_view()), name='motorcycle_brand_model_list'),  
    path('moto/marca/<int:brand_id>/modelo/<int:model_id>', login_required(views.EditMotorcycleBrandModelAdminView.as_view()), name='motorcycle_brand_model_edit'),  
    path('moto/marca/<int:brand_id>/modelo/<int:model_id>/remover', login_required(views.DeleteMotorcycleBrandModelAdminView.as_view()), name='motorcycle_brand_model_delete'),  

    path('moto/marca/modelo/versao', login_required(views.SelectMotorcycleBrandModelVersionAdminView.as_view()), name='motorcycle_brand_model_version_select'),  
    path('moto/marca/modelo/versao/novo', login_required(views.AddMotorcycleBrandModelVersionAdminView.as_view()), name='motorcycle_brand_model_version_add'),     
    path('moto/marca/<int:brand_id>/modelo/<int:model_id>/versao', login_required(views.ListMotorcycleBrandModelVersionAdminView.as_view()), name='motorcycle_brand_model_version_list'),      
    path('moto/marca/<int:brand_id>/modelo/<int:model_id>/versao/<int:version_id>', login_required(views.EditMotorcycleBrandModeVersionlAdminView.as_view()), name='motorcycle_brand_model_version_edit'),  
    path('moto/marca/modelo/versao/<int:version_id>/remover', login_required(views.DeleteMotorcycleBrandModelVersionAdminView.as_view()), name='motorcycle_brand_model_version_delete'),  

    #path('motorcycle/brand/<str:brand_id>/model/<int:model_id>/version/<int:version_id>', login_required(views.EditMotorcycleAdminView.as_view()), name='edit'),
]

webapp/motando/motandoadm/forms.py
#
# motandoadm/forms.py
#

from django import forms

from motorcycle.models import MotorcycleBrand, MotorcycleBrandModel, MotorcycleBrandModelVersion


class MotorcycleBrandForm(forms.ModelForm):    
    class Meta:
        model = MotorcycleBrand
        fields = ('brand',)
        labels = {'brand': 'Marca'}

        widgets = {
            'brand': forms.TextInput(attrs={'class': 'form-control'})
        }


class MotorcycleBrandModelForm(forms.ModelForm):        
    class Meta:
        model = MotorcycleBrandModel
        fields = ('brand', 'model',)
        labels = {'brand': 'Marca', 'model': 'Modelo'}

        widgets = {
            'brand': forms.Select(attrs={'class': 'form-control', 'readonly': True}),
            'model': forms.TextInput(attrs={'class': 'form-control'})
        }


class MotorcycleBrandModelVersionForm(forms.ModelForm):        
    class Meta:
        model = MotorcycleBrandModelVersion
        fields = ('model', 'version',)
        labels = {'model': 'Marca - Modelo', 'version': 'Versão'}

        widgets = {        
            'model': forms.Select(attrs={'class': 'form-control', 'readonly': True}),
            'version': forms.TextInput(attrs={'class': 'form-control'})
        }

webapp/motando/motandoadm/views.py
#
# motandoadm/views.py
#

from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import Http404


from motorcycle.models import MotorcycleBrand, MotorcycleBrandModel, MotorcycleBrandModelVersion
from .forms import MotorcycleBrandForm, MotorcycleBrandModelForm, MotorcycleBrandModelVersionForm


class SuperUserRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    """Classe para verificar se o usuário é um super usuário."""
    def test_func(self):
        return self.request.user.is_superuser


class HomeAdminView(SuperUserRequiredMixin, View):
    def get(self, request):
        return render(request, 'motandoadm/home.html', {})        


class ListAllMotorcycleAdminView(SuperUserRequiredMixin, View):
    def get(self, request):
        return render(request, 'motandoadm/motorcycle_all.html', {}) 


class ListMotorcycleBrandAdminView(SuperUserRequiredMixin, View):
    def get(self, request):
        brand_list = MotorcycleBrand.objects.all()        
        paginator = Paginator(brand_list, 10)
                        
        page_number = request.GET.get('p')        
        brands_page = paginator.get_page(page_number)

        return render(request, 'motandoadm/motorcycle_brand_list.html', 
            {'brands_page': brands_page})
    

class AddMotorcycleBrandAdminView(SuperUserRequiredMixin, View):
    def get(self, request):
        form = MotorcycleBrandForm()

        return render(request, 'motandoadm/motorcycle_brand.html', {'form': form})
    
    def post(self, request):
        form = MotorcycleBrandForm(request.POST)

        if form.is_valid():
            form.save()

            messages.success(request, 'Moto Marca cadastrada com sucesso.')
        else:
            messages.error(request, 'Erro ao cadastrar Moto Marca.')
        
        return redirect('motandoadm:motorcycle_brand_list')


class EditMotorcycleBrandAdminView(SuperUserRequiredMixin, View):
    def get(self, request, brand_id: int):
        try:
            brand = MotorcycleBrand.objects.filter(id=brand_id).get()
        except MotorcycleBrand.DoesNotExist:
            raise Http404

        form = MotorcycleBrandForm(initial={'brand': brand.brand})

        return render(request, 'motandoadm/motorcycle_brand.html', 
            {'form': form, 'brand_id': brand_id})
    
    def post(self, request, brand_id: int):
        try:
            brand = MotorcycleBrand.objects.filter(id=brand_id).get()
        except MotorcycleBrand.DoesNotExist:
            raise Http404        

        form = MotorcycleBrandForm(request.POST, instance=brand)

        if form.is_valid():
            form.save()

            messages.success(request, 'Moto Marca atualizada com sucesso.')
        else:           
            messages.error(request, 'Erro ao atualizar Moto Marca.')
        
        return redirect('motandoadm:motorcycle_brand_list')


class DeleteMotorcycleBrandAdminView(SuperUserRequiredMixin, View):
    def get(self, request, brand_id: int):
        try:
            brand = MotorcycleBrand.objects.filter(id=brand_id).get()
        except MotorcycleBrand.DoesNotExist:
            raise Http404    
        
        return render(request, 'motandoadm/motorcycle_brand_delete.html', {'brand': brand})

    def post(self, request, brand_id: int):
        try:
            brand = MotorcycleBrand.objects.filter(id=brand_id).get()
        except MotorcycleBrand.DoesNotExist:
            raise Http404
                
        deleted = brand.delete()
      
        if deleted[0] == 1:
             messages.success(request, 'Moto Marca excluída com sucesso.')
        else:           
            messages.error(request, 'Erro ao excluir Moto Marca.')

        return redirect('motandoadm:motorcycle_brand_list')


class SelectMotorcycleBrandModelAdminView(SuperUserRequiredMixin, View):
    def get(self, request):       
        return render(request, 'motandoadm/motorcycle_brand_model_select.html', {})


class AddMotorcycleBrandModelAdminView(SuperUserRequiredMixin, View):
    def get(self, request):        
        form = MotorcycleBrandModelForm()

        return render(request, 'motandoadm/motorcycle_brand_model.html', 
            {'form': form})
    
    def post(self, request):
        form = MotorcycleBrandModelForm(data=request.POST)
        
        if form.is_valid():
            form.save()

            messages.success(request, 'Moto Modelo cadastrado com sucesso.')
        else:
            messages.error(request, 'Erro ao cadastrar Moto Moto Modelo.')
        
        return redirect('motandoadm:motorcycle_brand_model_add')
    

class ListMotorcycleBrandModelAdminView(SuperUserRequiredMixin, View):
    def get(self, request, brand_id: int):       
        try:
            motorcycle_model_list = MotorcycleBrandModel.objects.filter(brand__id=brand_id).all()
        except MotorcycleBrandModel.DoesNotExist:
            raise Http404
                     
        paginator = Paginator(motorcycle_model_list, 10)

        page_number = request.GET.get('p')        
        motorcycle_models_page = paginator.get_page(page_number)

        return render(request, 'motandoadm/motorcycle_brand_model_list.html', 
            {'brand_id': brand_id, 'motorcycle_models_page': motorcycle_models_page})


class EditMotorcycleBrandModelAdminView(SuperUserRequiredMixin, View):
    def get(self, request, brand_id: int, model_id: int):         
        motorcycle_model = get_object_or_404(MotorcycleBrandModel, id=model_id)
        
        form = MotorcycleBrandModelForm(instance=motorcycle_model)

        return render(request, 'motandoadm/motorcycle_brand_model.html', 
            {'form': form, 'brand_id': brand_id, 'model_id': model_id})
    
    def post(self, request, brand_id: int, model_id: int):
        motorcycle_model = get_object_or_404(MotorcycleBrandModel, id=model_id)
        
        form = MotorcycleBrandModelForm(request.POST, instance=motorcycle_model)
                                                          
        if form.is_valid():            
            form.save()            

            messages.success(request, 'Moto Marca Modelo atualizado com sucesso.')
        else:           
            messages.error(request, 'Erro ao atualizar Moto Marca Modelo.')
        
        return redirect('motandoadm:motorcycle_brand_model_list', brand_id=brand_id)


class DeleteMotorcycleBrandModelAdminView(SuperUserRequiredMixin, View):
    def get(self, request, brand_id: int, model_id: int): 
        motorcycle_model = get_object_or_404(MotorcycleBrandModel, id=model_id)

        return render(request, 'motandoadm/motorcycle_brand_model_delete.html', {'motorcycle_model': motorcycle_model})

    def post(self, request, brand_id: int, model_id: int): 
        motorcycle_model = get_object_or_404(MotorcycleBrandModel, id=model_id)

        deleted = motorcycle_model.delete()

        if deleted[0] == 1:
             messages.success(request, 'Moto Modelo excluído com sucesso.')
        else:           
            messages.error(request, 'Erro ao excluir Moto Modelo.')

        return redirect('motandoadm:motorcycle_brand_model_list', brand_id=brand_id)


class SelectMotorcycleBrandModelVersionAdminView(SuperUserRequiredMixin, View):
    def get(self, request):       
        return render(request, 'motandoadm/motorcycle_brand_model_version_select.html', {})


class AddMotorcycleBrandModelVersionAdminView(SuperUserRequiredMixin, View):
    pass


class ListMotorcycleBrandModelVersionAdminView(SuperUserRequiredMixin, View):
    def get(self, request, brand_id: int, model_id: int): 
        try:
            motorcycle_version_list = MotorcycleBrandModelVersion.objects.filter(model__brand__id=brand_id, 
                model__id=model_id).all()
        except MotorcycleBrandModelVersion.DoesNotExist:
            raise Http404
        
        paginator = Paginator(motorcycle_version_list, 10)

        page_number = request.GET.get('p')        
        motorcycle_versions_page = paginator.get_page(page_number)

        return render(request, 'motandoadm/motorcycle_brand_model_version_list.html', 
            {'motorcycle_versions_page': motorcycle_versions_page})


class EditMotorcycleBrandModeVersionlAdminView(SuperUserRequiredMixin, View):
    def get(self, request, brand_id: int, model_id: int, version_id: int):         
        motorcycle_version = get_object_or_404(MotorcycleBrandModelVersion, id=version_id)
        
        form = MotorcycleBrandModelVersionForm(instance=motorcycle_version)

        return render(request, 'motandoadm/motorcycle_brand_model_version.html', 
            {'form': form, 'brand_id': brand_id, 'model_id': model_id, 'version_id': version_id})

    def post(self, request, brand_id: int, model_id: int, version_id: int):  
        motorcycle_version = get_object_or_404(MotorcycleBrandModelVersion, id=version_id)
        
        form = MotorcycleBrandModelVersionForm(request.POST, instance=motorcycle_version)
                                                          
        print(form)

        if form.is_valid():            
            form.save()            

            messages.success(request, 'Moto Modelo Versão atualizado com sucesso.')
        else:           
            messages.error(request, 'Erro ao atualizar Moto Modelo Versão.')
        
        return redirect('motandoadm:motorcycle_brand_model_version_list', brand_id=brand_id, 
            model_id=model_id)


class DeleteMotorcycleBrandModelVersionAdminView(SuperUserRequiredMixin, View):
    def get(self, request, version_id: int):
        motorcycle_version = get_object_or_404(MotorcycleBrandModelVersion, id=version_id)       
        
        return render(request, 'motandoadm/motorcycle_brand_model_version_delete.html', 

webapp/motando/motandoadm/templates/motandoadm/include/base.html
<!doctype html>{% spaceless %} 
<html lang="pt-br">
<head>    
    {% load static %}
    {% block head %}        
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">        
        <meta name="robots" content="noindex, nofollow">
        <link href="{% static '/motandoadm/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
        <link href="{% static '/motandoadm/css/sb-admin-2.min.css' %}" rel="stylesheet">
        <title>{% block title %}{% endblock %} | Motando</title>        
    {% endblock %}               
</head>
<body id="page-top"> 
    <div id="wrapper">
        {% include "motandoadm/include/left-menu.html" %}
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                {% include "motandoadm/include/top-menu.html" %}
                {% block body %}        
                {% endblock %}  
            </div>
        </div>
    </div>
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="id_logout_modal"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="id_logout_modal">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{% url 'account:logout' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>    
    {% block footer %}    
       <br><br>
    {% endblock %}        
        <script src="{% static '/motandoadm/vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static '/motandoadm/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>           
        <script src="{% static '/motandoadm/vendor/jquery-easing/jquery.easing.min.js' %}"></script>    
        <script src="{% static '/motandoadm/js/sb-admin-2.min.js' %}"></script>   
        <!--
        <script src="{% static '/motandoadm/vendor/chart.js/Chart.min.js' %}"></script>    
        <script src="{% static '/motandoadm/js/demo/chart-area-demo.js' %}"></script>
        <script src="{% static '/motandoadm/js/demo/chart-pie-demo.js' %}"></script> 
        //--> 
    {% block body_scripts %}
    {% endblock %}   
</body>
</html>{% endspaceless %}  

webapp/motando/motandoadm/templates/motandoadm/include/left-menu.html
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3"><sup>Motando Admin</sup></div>
    </a>    
    <hr class="sidebar-divider my-0">    
    <li class="nav-item active">
        <a class="nav-link" href="index.html">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>    
    <hr class="sidebar-divider">    
    <div class="sidebar-heading">
        Administração
    </div> 
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapse-motorcycle"
            aria-expanded="true" aria-controls="collapse-motorcycle">
            <i class="fa fa-motorcycle"></i>
            <span>Motos</span>
        </a>
        <div id="collapse-motorcycle" class="collapse" aria-labelledby="heading-motorcycle"
             data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <a class="collapse-item" href="{% url 'motandoadm:motorcycle_all_list' %}">Exibir Todas</a>
                <hr class="w-75">
                <h6 class="collapse-header">Marca</h6>
                <a class="collapse-item" href="{% url 'motandoadm:motorcycle_brand_list' %}">Listar</a>
                <a class="collapse-item" href="{% url 'motandoadm:motorcycle_brand_add' %}">Adicionar</a>                
                <hr class="w-75">        
                <h6 class="collapse-header">Modelo</h6>
                <a class="collapse-item" href="{% url 'motandoadm:motorcycle_brand_model_select' %}">Listar</a>
                <a class="collapse-item" href="{% url 'motandoadm:motorcycle_brand_model_add' %}">Adicionar</a>   
                <hr class="w-75">        
                <h6 class="collapse-header">Versão</h6>
                <a class="collapse-item" href="{% url 'motandoadm:motorcycle_brand_model_version_select' %}">Listar</a>
                <a class="collapse-item" href="{% url 'motandoadm:motorcycle_brand_model_version_add' %}">Adicionar</a>               
            </div>            
        </div>        
    </li>   
    <li class="nav-item">
        <a class="nav-link" href="charts.html">
            <i class="fa fa-globe"></i>
            <span>Estado & Cidade</span>
        </a>
    </li>   
    <!--
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
            aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-cog"></i>
            <span>Motos</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">                
                <a class="collapse-item" href="buttons.html">Buttons</a>
                <a class="collapse-item" href="cards.html">Cards</a>
            </div>
        </div>
    </li>    
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapse-motorcycle"
            aria-expanded="true" aria-controls="collapse-motorcycle">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Utilities</span>
        </a>
        <div id="collapse-motorcycle" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Utilities:</h6>
                <a class="collapse-item" href="utilities-color.html">Colors</a>
                <a class="collapse-item" href="utilities-border.html">Borders</a>
                <a class="collapse-item" href="utilities-animation.html">Animations</a>
                <a class="collapse-item" href="utilities-other.html">Other</a>
            </div>
        </div>
    </li>
    <hr class="sidebar-divider">
    <div class="sidebar-heading">
        Addons
    </div>
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
            aria-expanded="true" aria-controls="collapsePages">
            <i class="fas fa-fw fa-folder"></i>
            <span>Pages</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Login Screens:</h6>
                <a class="collapse-item" href="login.html">Login</a>
                <a class="collapse-item" href="register.html">Register</a>
                <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
                <div class="collapse-divider"></div>
                <h6 class="collapse-header">Other Pages:</h6>
                <a class="collapse-item" href="404.html">404 Page</a>
                <a class="collapse-item" href="blank.html">Blank Page</a>
            </div>
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="tables.html">
            <i class="fas fa-fw fa-table"></i>
            <span>Tables</span></a>
    </li>
    <hr class="sidebar-divider d-none d-md-block">
    //-->
    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
    <!-- Sidebar Message 
    <div class="sidebar-card d-none d-lg-flex">
        <img class="sidebar-card-illustration mb-2" src="img/undraw_rocket.svg" alt="...">
        <p class="text-center mb-2"><strong>SB Admin Pro</strong> is packed with premium features, components, and more!</p>
        <a class="btn btn-success btn-sm" href="https://startbootstrap.com/theme/sb-admin-pro">Upgrade to Pro!</a>
    </div>
    -->
</ul>

webapp/motando/motandoadm/templates/motandoadm/include/messages.html
{% if messages %}
    {% for message in messages %}        
        <div class="row align-items-center text-center w-100">                                                                      
            <div class="col">
                {% if message.tags == 'error' %}                   
                   <div class="h5 alert alert-danger" role="alert"> {{ message|safe }} </div>
                {% elif message.tags == 'success' %}
                   <div class="alert alert-success h5" role="alert"> {{ message|safe }} </div>                
                {% elif message.tags == 'warning' %}
                   <div class="alert alert-warning h5" role="alert"> {{ message|safe }} </div>
                {% else %}
                   <div class="alert alert-info h5" role="alert"> {{ message|safe }} </div>
                {% endif %}              
            </div>
        </div> 
    {% endfor %}
{% endif %}