webapp/motando/account/urls.py
#
# account/urls.py
#

from django.urls import path
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'account'

urlpatterns = [
    path('login', views.user_login, name='login'),
    path('logout', login_required(views.user_logout), name='logout'),

    path('registro', TemplateView.as_view(template_name='account/choices.html'), name='choices'),
    path('new/user', views.NewUserView.as_view(), name='new_user'),
    path('new/user/success', TemplateView.as_view(template_name='account/confirmation.html'), 
         name='new_user_success'),

    path('user/home', login_required(views.UserProfileHomeView.as_view()), name='home'),
    path('user/profile', login_required(views.UserProfileView.as_view()), name='profile'),
    path('user/password_and_security', login_required(views.UserPasswordSecurityView.as_view()), name='password_security'),
]

webapp/motando/chat/urls.py
#
# chat/urls.py
#

from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'chat'

urlpatterns = [    
    path('home', login_required(views.ChatHomeView.as_view()), name='home'),    
]

webapp/motando/classifiedad/urls.py
#
# classifiedad/urls.py
#

from django.urls import path
from django.contrib.auth.decorators import login_required

from classifiedad import views

app_name = 'classifiedad'

urlpatterns = [

    # Visualização particular (tela administrativa)
    path('home', login_required(views.HomeClassifiedAdView.as_view()), name='home'),
    path('new', login_required(views.NewClassifiedAdView.as_view()), name='new'),
    path('upload/image', login_required(views.ClassifiedAdTmpImageUploadView.as_view()), name='image_upload'),
    path('edit/<int:classifiedad_id>', login_required(views.EditClassifiedAdView.as_view()), name='edit'),   
    path('delete', login_required(views.DeleteClassifiedAdView.as_view()), name='delete'),   

    # Visualização pública
    path('<str:brand>/<str:model>/<int:model_year>/<int:classifiedad_id>', views.ClassifiedAdDetailView.as_view(), name='detail'),
    path('all', views.AllClassifiedAdView.as_view(), name='all')
]

webapp/motando/home/urls.py
#
# home/urls.py
#

from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.MainPageView.as_view(), name='main_page'),         
]

webapp/motando/motando/urls.py
from django.urls import path, include

urlpatterns = [
    # Admin Site
    path('motandoadm/', include('motandoadm.urls', namespace='motandoadm')),

    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
    path('classifiedad/', include('classifiedad.urls', namespace='classifiedad')),
    path('chat/', include('chat.urls', namespace='chat')),   

    # API
    path('api/brazil/', include('state_city.api.urls', namespace='api_state_city')),
    path('api/motorcycles/', include('motorcycle.api.urls', namespace='api_motorcycle')),
    path('api/classifiedads/', include('classifiedad.api.urls', namespace='api_classifiedad')),
    path('api/chats/', include('chat.api.urls', namespace='api_chat')),
]

webapp/motando/templates/footer.html
<footer>{% spaceless %} 
    <div class="container-fluid" id="id_footer_motando_anuncio_container">        
        <div class="row pt-4">
            <div class="col-md-12 col-sm-12 text-center">
                <h3 class="h1"><strong>Quer Vender Sua moto?</strong></h3>
                <h3 class="h3 pt-2"><strong>Anuncie grátis agora mesmo!</strong></h3>      
            </div>
        </div>          
        <div class="row pt-4">
            <div class="col-md-12 col-sm-12 d-flex justify-content-center">
                <a href="{% url 'classifiedad:new' %}" class="btn btn-success btn-lg fw-bold" 
                   id="id_link_motando_anuncio" >
                        &nbsp;&nbsp;&nbsp; Anunciar &nbsp;&nbsp;&nbsp;
                </a>
            </div>
        </div>       
        <br>
    </div>        
    <div class="container-fluid" id="id_footer_newsletter_container">        
        <form>                
                <div class="row p-4">
                    <div class="col-md col-sm text-right">
                        <p class="pt-2 h5"> Receba nossas notícias </p>
                    </div>            
                    <div class="col-md-4 col-sm-4 pt-2 pb-2">
                        <input type="text" class="form-control" placeholder="Nome">
                    </div>
                    <div class="col-md-4 col-sm-4 pt-2 pb-2">
                        <input type="email" class="form-control" placeholder="E-mail">
                    </div>
                    <div class="col-md col-sm pt-2 pb-2">
                        <button type="submit" class="btn btn-success btn-block fw-bold"> 
                            &nbsp;&nbsp;&nbsp; Enviar &nbsp;&nbsp;&nbsp; 
                        </button>
                    </div>            
                </div>
        </form>
    </div>
    <div class="container-fluid" id="id_footer_container"> 
        <div class="row p-4">
            <div class="col-md-12 col-sm-12 d-flex justify-content-center">
                <p class="pt-2">
                    © Copyright - 2020 | MOTANDO.com.br | Todos os direitos reservados | All Rights reserved | 
                    <a href="#">Termos de uso</a>
                </p>
            </div>
        </div>       
    </div>
</footer>{% endspaceless %} 

webapp/motando/templates/messages.html
{% spaceless %}
{% if messages %}
    {% for message in messages %}        
        <div class="row align-items-center text-center w-100">                                                                      
            <div class="col-md col-sm">
                {% if message.tags == 'error' %}                   
                   <div class="h5 alert alert-danger" role="alert"> {{ message|safe }} </div>
                {% elif message.tags == 'success' %}
                   <div class="alert alert-success h5" role="alert"> {{ message|safe }} </div>                
                {% elif message.tags == 'warning' %}
                   <div class="alert alert-warning h5" role="alert"> {{ message|safe }} </div>
                {% else %}
                   <div class="alert alert-info h5" role="alert"> {{ message|safe }} </div>
                {% endif %}              
            </div>
        </div> 
    {% endfor %}
{% endif %}{% endspaceless %}

webapp/motando/templates/navbar_anonymous.html
<header id="id_header_navbar">{% spaceless %}
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light fixed-top">
    <div class="container-fluid">
       <button class="navbar-toggler" type="button"
               data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
               aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
       </button>
       <a class="navbar-brand offset-md-1 offset-sm-1 d-none d-md-block" href="{% url 'home:main_page' %}">
           <img src="{% static 'img/home-icon_100x86.png' %}" alt="Motando" width="30" class="img-fluid">
       </a>       
       <div class="collapse navbar-collapse" id="navbarNavDropdown">
         <ul class="navbar-nav">           
           <li class="nav-item dropdown dropdown-hover">
             <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" 
                role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Comprar
             </a>
             <ul class="dropdown-menu dropdown-hover-menu" aria-labelledby="navbarDropdownMenuLink">
               <li><a class="dropdown-item" href="{% url 'classifiedad:all' %}">Todos os Anúncios</a></li>
               {% comment %}
                  <li><a class="dropdown-item" href="#">Lojas Oficiais</a></li>
                  <li><a class="dropdown-item" href="#">Busca Avançada</a></li>
               {% endcomment %}
             </ul>
           </li>
           <li class="nav-item">
               <a class="nav-link" href="{% url 'classifiedad:new' %}">Vender</a>
           </li>
           <li class="nav-item">
               <a class="nav-link" href="#">Notícias</a>
           </li>
         </ul>
       </div>
       <span class="navbar-text">        
            <a href="{% url 'account:login' %}" class="h5 text-decoration-none">
               <i class="fas fa-user-alt"></i> Entrar &nbsp;
            </a>                  
       </span>
    </div>
</nav>
</header>{% endspaceless %}

webapp/motando/templates/navbar_authenticated.html
<header id="id_header_navbar">{% spaceless %}
{% load static %}
<!-- Mobile Navbar -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top d-sm-block d-md-none d-lg-none d-xl-none d-xxl-none">
    <div class="container-fluid">
       <button class="navbar-toggler" type="button"
               data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
               aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
       </button>         
       <div class="collapse navbar-collapse" id="navbarNavDropdown">
         <ul class="navbar-nav pt-2">  
           <li class="nav-item dropdown dropdown-hover">
               <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" 
                  data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="fa fa-shopping-cart"></i>
                  &nbsp;Comprar
               </a>
               <ul class="dropdown-menu dropdown-hover-menu" aria-labelledby="navbarDropdownMenuLink">
                    <li>
                        <a class="dropdown-item" href="{% url 'classifiedad:all' %}">
                           Todos os Anúncios
                        </a>
                    </li>
                    {% comment %}
                      <li><a class="dropdown-item" href="#">Lojas Oficiais</a></li>
                      <li><a class="dropdown-item" href="#">Busca Avançada</a></li>
                    {% endcomment %}
               </ul>
           </li>
           <li class="nav-item">
              <hr>
           </li>   
           <li class="nav-item">
               <a class="nav-link" href="{% url 'account:home' %}">
                  <i class="fa fa-user-circle"></i> 
                  &nbsp;Minha Conta
               </a>
           </li>
           <li class="nav-item">
               <a class="nav-link" href="{% url 'classifiedad:new' %}">
                   <i class="fas fa-plus-circle"></i> 
                   &nbsp;Novo Anúncio
               </a>
           </li>
           <li class="nav-item">
               <a class="nav-link" href="{% url 'classifiedad:home' %}">
                   <i class="fab fa-leanpub"></i> 
                   &nbsp;Meus Anúncios
               </a>
           </li>
           <li class="nav-item">
               <a class="nav-link" href="{% url 'chat:home' %}">
                   <i class="fas fa-comments"></i> 
                   &nbsp;Chat de Propostas                    
               </a>
           </li>
           <li class="nav-item">
               <a class="nav-link" href="{% url 'account:profile' %}">                     
                   <i class="fas fa-user-cog"></i> 
                   &nbsp;Minha Conta
               </a>
           </li>
           <li class="nav-item">
              <a class="nav-link" href="{% url 'account:password_security' %}">                     
                   <i class="fa-solid fa-key"></i> 
                   &nbsp;Senha e Segurança                      
              </a>
           </li>
           <li class="nav-item">
              <a class="nav-link" href="#">                     
                   <i class="fas fa-star"></i> 
                   &nbsp;Favoritos                   
              </a>
           </li>
           <li class="nav-item">
              <a class="nav-link" href="#">                     
                   <i class="fa fa-motorcycle"></i> 
                   &nbsp;Notícias                   
              </a>
           </li>   
           <li class="nav-item">
               <hr>
           </li>          
         </ul>
       </div>
       <span class="navbar-text">        
            <a href="{% url 'account:logout' %}" class="text-decoration-none">
                <i class="fa fa-sign-out"></i> 
                &nbsp;Sair 
            </a>         
         &nbsp;
       </span>
    </div>
</nav>

<!-- Desktop Navbar -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top d-none d-md-block">
    <div class="container-fluid">
       <button class="navbar-toggler" type="button"
               data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
               aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
       </button>
       <a class="navbar-brand offset-md-1 offset-sm-1 d-md-none d-lg-block" href="{% url 'home:main_page' %}">
         <img src="{% static 'img/home-icon_100x86.png' %}" alt="Motando" width="30" class="img-fluid">
       </a>
       <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">           
                <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:home' %}">Minha Conta</a>
                </li>
                <li class="nav-item dropdown dropdown-hover">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Comprar
                        </a>
                        <ul class="dropdown-menu dropdown-hover-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'classifiedad:all' %}">Todos os Anúncios</a></li>
                        {% comment %}
                            <li><a class="dropdown-item" href="#">Lojas Oficiais</a></li>
                            <li><a class="dropdown-item" href="#">Busca Avançada</a></li>
                        {% endcomment %}
                        </ul>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="{% url 'classifiedad:new' %}">Vender</a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="#">Notícias</a>
                </li>
            </ul>
       </div>
       <span class="navbar-text">
            <a href="{% url 'account:logout' %}" class="h5 text-decoration-none">
               <i class="fas fa-user-alt"></i> Sair &nbsp;&nbsp;
            </a>        
         &nbsp;&nbsp;&nbsp;
       </span>
    </div>
</nav>
</header>{% endspaceless %}