webapp/motando/chat/api/urls.py
#
# chat/api/urls.py
#

from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    # Public endpoint.
    path('messages', views.PublicChatMessageApiView.as_view(), name='public_message'),    

    # Private endpoint (needs authentication).
    path('messages/buying/participants', 
         views.ChatBuyingParticipantsListApiView.as_view(), name='buying_participant_list'),    

    path('<int:chat_id>/messages/buying',
         views.ChatBuyingMessagesListApiView.as_view(), name='buying_participant_id'),    

    path('messages/selling/participants', 
         views.ChatSellingParticipantsListApiView.as_view(), name='selling_participant_list'),  

    path('<int:chat_id>/messages/selling', 
         views.ChatSellingMessagesListApiView.as_view(), name='selling_messages_list'),   

    path('<int:chat_id>/messages', views.ChatMessageApiView.as_view(), name='message'),
]

webapp/motando/chat/urls.py
#
# chat/urls.py
#

from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'chat'

urlpatterns = [    
    path('home', login_required(views.ChatHomeView.as_view()), name='home'),    
]

webapp/motando/home/urls.py
#
# home/urls.py
#

from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.MainPageView.as_view(), name='main_page'),         
]

webapp/motando/motando/urls.py
from django.urls import path, include

urlpatterns = [
    # Admin Site
    path('motandoadm/', include('motandoadm.urls', namespace='motandoadm')),

    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
    path('classifiedad/', include('classifiedad.urls', namespace='classifiedad')),
    path('chat/', include('chat.urls', namespace='chat')),   

    # API
    path('api/brazil/', include('state_city.api.urls', namespace='api_state_city')),
    path('api/motorcycles/', include('motorcycle.api.urls', namespace='api_motorcycle')),
    path('api/classifiedads/', include('classifiedad.api.urls', namespace='api_classifiedad')),
    path('api/chats/', include('chat.api.urls', namespace='api_chat')),
]

webapp/motando/chat/models.py
#
#  
#

from django.db import models
from django.conf import settings


from classifiedad.models import ClassifiedAd


class Chat(models.Model):
    classifiedad = models.ForeignKey(ClassifiedAd, on_delete=models.DO_NOTHING, null=False, blank=False)
    user_to = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, null=False, blank=False, related_name='user_to')
    user_from = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, null=True, default=None, related_name='user_from')
    user_from_fullname = models.CharField(max_length=200, null=True, blank=False)
    user_from_email = models.EmailField(null=True, blank=False)
    user_from_telephone = models.CharField(max_length=40, null=True, blank=False)  
    messages = models.JSONField(null=False, blank=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'chats'
        ordering = ['created']

webapp/motando/chat/api/views.py
#
# chat/api/views.py
#

from rest_framework import views,  status
from rest_framework.response import Response
from rest_framework.authentication import SessionAuthentication
from rest_framework.permissions import IsAuthenticated

from chat.api.serializers import PublicMessageSerializer, ChatMessageSerializer, \
    ChatSellingParticipantListSerializer, ChatSellingMessagesListSerializer, \
    ChatBuyingParticipantListSerializer, ChatBuyingMessagesListSerializer

from chat.models import Chat


class PublicChatMessageApiView(views.APIView):    
    authentication_classes = (SessionAuthentication,)

    def post(self, request):
        if request.data.get('email_from') == request.data.get('email_to'):
            return Response({'status': 'fail', 'message': 'Unable to create new Chat message.'},
                            status=status.HTTP_400_BAD_REQUEST) 
      
        serializer = PublicMessageSerializer(data=request.data)
       
        if serializer.is_valid():
            serializer.save()

            return Response({'status': 'success', 'message': 'The message was successful send.'},
                            status=status.HTTP_200_OK) 
        
        else:        
            return Response({'status' : 'fail', 'message' : 'Unable to process new Chat message.', 
                             'data': serializer.errors}, status=status.HTTP_400_BAD_REQUEST)     
    

class ChatMessageApiView(views.APIView):    
    authentication_classes = (SessionAuthentication,)
    permission_classes = (IsAuthenticated,)

    def post(self, request, chat_id):
        serializer = ChatMessageSerializer(data=request.data)

        print(request.data)

        if serializer.is_valid():
            serializer.save()

            return Response({'status': 'success', 'message': 'The message was successful send.'},
                            status=status.HTTP_200_OK) 
        
        else:        
            return Response({'status' : 'fail', 'message' : 'Unable to process new Chat message.', 
                             'data': serializer.errors}, status=status.HTTP_400_BAD_REQUEST)     


class ChatBuyingParticipantsListApiView(views.APIView):
    authentication_classes = (SessionAuthentication,)
    permission_classes = (IsAuthenticated,)

    def get(self, request):        
        chat = Chat.objects.filter(user_from_email=request.user.email,                                                          
                                   classifiedad__status='PUBLISHED')
        
        if not chat.exists():
            return Response(data={'status': 'fail', 'message': 'No Chat Message(s) found.'},
                            status=status.HTTP_404_NOT_FOUND)
        
        serializer = ChatBuyingParticipantListSerializer(chat, many=True)

        return Response(data={'status' : 'success', 'data': serializer.data},
                        status=status.HTTP_200_OK)


class ChatBuyingMessagesListApiView(views.APIView):
    authentication_classes = (SessionAuthentication,)
    permission_classes = (IsAuthenticated,)

    def get(self, request, chat_id):
        chat = Chat.objects.filter(id=chat_id, 
                                   user_from_email=request.user.email,                                                    
                                   classifiedad__status='PUBLISHED')
        
        if not chat.exists():
            return Response(data={'status': 'fail', 'message': 'No Chat Message(s) found.'},
                            status=status.HTTP_404_NOT_FOUND)
        
        serializer = ChatBuyingMessagesListSerializer(chat, many=True)

        return Response(data={'status' : 'success', 'data': serializer.data},
                        status=status.HTTP_200_OK)


class ChatSellingParticipantsListApiView(views.APIView):
    authentication_classes = (SessionAuthentication,)
    permission_classes = (IsAuthenticated,)

    def get(self, request):
        chat = Chat.objects.filter(user_to__id=request.user.id,                
                                   user_to__is_active=True,        
                                   classifiedad__status='PUBLISHED')
        
        if not chat.exists():
            return Response(data={'status': 'fail', 'message': 'No Chat Message(s) found.'},
                            status=status.HTTP_404_NOT_FOUND)
        
        serializer = ChatSellingParticipantListSerializer(chat, many=True)

        return Response(data={'status' : 'success', 'data': serializer.data},
                        status=status.HTTP_200_OK)
     

class ChatSellingMessagesListApiView(views.APIView):
    authentication_classes = (SessionAuthentication,)
    permission_classes = (IsAuthenticated,)

    def get(self, request, chat_id):
        chat = Chat.objects.filter(id=chat_id,
                                   user_to__id=request.user.id,                
                                   user_to__is_active=True,        
                                   classifiedad__status='PUBLISHED')
        
        if not chat.exists():
            return Response(data={'status': 'fail', 'message': 'No Chat Message(s) found.'},
                            status=status.HTTP_404_NOT_FOUND)
        

        serializer = ChatSellingMessagesListSerializer(chat, many=True)

        return Response(data={'status' : 'success', 'data': serializer.data},
                        status=status.HTTP_200_OK)

webapp/motando/chat/views.py
#
# home/views.py
#

from django.shortcuts import render, get_object_or_404
from django.views import View

from account.models import UserProfile


class ChatHomeView(View):
    def get(self, request):
        user_profile = get_object_or_404(UserProfile, user=request.user)

        return render(request, 'chat/home.html', {'user_profile': user_profile})
 

webapp/motando/home/views.py
#
# home/views.py
#

from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View

from classifiedad.models import ClassifiedAd


class MainPageView(View):
    def get(self, request):
        max_top_classifiedad = 15

        top_classifiedad =  ClassifiedAd.objects.filter(status='published',
                                                        top_offer=True).all().order_by('-updated')[:max_top_classifiedad]

        return render(request, 'home.html', {
            'top_classifiedad': top_classifiedad
        })
    
    def post(self, request):
        search_url = request.POST.get('search_url', None)

        if search_url:            
            next_url = reverse('classifiedad:all') + '?q=' + search_url
        else:
            next_url = reverse('classifiedad:all')
        
        return redirect(next_url)
            

webapp/motando/chat/templates/chat/home.html
{% extends "account_layout/base.html" %}
{% spaceless %}
{% load static %}
{% block head %}
    {{ block.super }}
    <style type="text/css">
        body { padding-top: 80px; }
    </style>
{% endblock %}
{% block title %} Chat de Propostas {% endblock %}
{% block body %}
   {{ block.super }}     
   <section>
       <div class="container">     
            <div class="row">               
                  <div class="col-md-3 col-sm-3 d-flex justify-content-center">
                      <a href="{% url 'account:home' %}">
                        <img src="{% static 'img/motando_logo-402x150.png' %}" class="img-fluid" alt="Motando" 
                             style="width: 220px;">
                      </a>
                  </div>         
                  <div class="col-md-9 col-sm-9 d-flex justify-content-center">                                
                     {% include "messages.html" %}      
                 </div>               
            </div>
            <div class="row">
               <!-- Visible only on desktop -->
               <div class="col-md-3 col-sm-3 d-none d-md-block">
                    {% include "account_layout/left_menu.html" with user_profile=user_profile %}  
               </div> 
               <div class="col-md-9 col-sm-9">
                  <br>
                  <form id="id_form_id" autocomplete="off">                     
                     {% csrf_token %}       
                     <div class="shadow rounded bg-white border p-3"  style="min-height: 700px;">
                         <div class="row">
                              <div class="col-md col-sm">
                                    <h2 class="h4 fw-bold"> Chat de Propostas </h2>  
                              </div>
                         </div>
                         <div class="row">                         
                              <div class="col-md col-sm">
                                    <p class="text-justify"> 
                                        Veja aqui a lista e histórico de suas negociações <b>via CHAT</b>, 
                                        por anúncio publicado, ativo ou arquivado. <br>
                                        Você também pode selecionar o anúncio e enviar uma mensagem. 
                                    </p>                               
                              </div>
                         </div>  
                         <div class="row m-2 pb-4">
                              <div class="col-md-auto col-sm-auto d-flex pt-2">
                                  <div class="form-check">
                                      <input class="form-check-input" type="radio" id="id_chat_selling" name="chat_options" value="selling">
                                      <label class="form-check-label" for="id_chat_selling">
                                         Vendendo 
                                      </label>
                                  </div>
                              </div>
                              <div class="col-md-auto col-sm-auto d-flex pt-2">
                                  <div class="form-check">
                                      <input class="form-check-input" type="radio" id="id_chat_buying" name="chat_options" value="buying">
                                      <label class="form-check-label" for="id_chat_buying">
                                          Comprando 
                                      </label>
                                  </div>
                              </div>
                              <div class="col-md-auto col-sm-auto d-flex pt-2">
                                 <div class="form-check">
                                       <input class="form-check-input" type="radio" id="id_chat_archive" name="chat_options" value="archive">
                                       <label class="form-check-label" for="id_chat_archive">
                                             Arquivado 
                                       </label>
                                 </div>
                              </div>
                         </div>
                         <div class="row d-none" id="id_chat_painel">
                              <input type="hidden" name="chat_id" id="id_chat_id" value=""> 
                              <div class="col-md-4 col-sm-4">
                                  <p class="fw-bold rounded-top my-background-purple text-white p-3 text-center"> Histórico de Conversas </p>  
                                  <div style="overflow-y: scroll; overflow-x: hidden;" id="id_chat_history">                                   
                                  </div>
                              </div>                            
                              <div class="col-md-8 col-sm-8">
                                  <p class="fw-bold rounded-top my-background-purple text-white p-3 text-left text-uppercase" 
                                      id="id_chat_from_fullname"> 
                                  </p>  
                                  <div style="overflow-y: scroll; overflow-x: hidden;"
                                        id="id_chat_messages">                                  
                                  </div>
                                  <br>
                                  <div class="input-group mb-3">
                                      <input type="text" class="form-control fst-italic" placeholder="Digite uma mensagem" 
                                              aria-label="Digite uma mensagem" aria-describedby="button-addon2" 
                                              id="id_chat_message" readonly>
                                      <button class="btn btn-success" type="button" id="id_button_sendmsg" disabled>
                                            &nbsp;&nbsp; Enviar &nbsp;&nbsp;
                                      </button>
                                  </div>                               
                              </div>
                         </div>
                     </div>
                  </form>
                  <div class="modal" tabindex="-1" id="id_modal">
                    <div class="modal-dialog modal-dialog-centered modal-lg">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="id_modal_title"></h5>
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                          <p id="id_modal_message"></p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>                                      
                        </div>
                      </div>
                    </div>
                </div> 
               </div> <!-- right panel -->      
            </div>
       </div>
   </section>
   <br><br> 
{% endblock %}
{% block body_scripts %}
   <script type="text/javascript" src="{% static 'vendor/jquery.blockUI.min.js' %}"></script> 
   <script type="text/javascript" src="{% static 'js/classifiedad-chat.js' %}"></script> 
   <script type="text/javascript">        
        const SELLING_PARTICIPANTS_URL = "{% url 'api_chat:selling_participant_list' %}";        
        const BUYING_PARTICIPANTS_URL = "{% url 'api_chat:buying_participant_list' %}";        
   </script>   
{% endblock %}
{% endspaceless %}