webapp/motando/chat/urls.py
#
# chat/urls.py
#

from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'chat'

urlpatterns = [    
    path('home', login_required(views.ChatHomeView.as_view()), name='home'),    
]

webapp/motando/home/urls.py
#
# home/urls.py
#

from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.MainPageView.as_view(), name='main_page'),         
]

webapp/motando/motando/urls.py
from django.urls import path, include

urlpatterns = [
    # Admin Site
    path('motandoadm/', include('motandoadm.urls', namespace='motandoadm')),

    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
    path('classifiedad/', include('classifiedad.urls', namespace='classifiedad')),
    path('chat/', include('chat.urls', namespace='chat')),   

    # API
    path('api/brazil/', include('state_city.api.urls', namespace='api_state_city')),
    path('api/motorcycles/', include('motorcycle.api.urls', namespace='api_motorcycle')),
    path('api/classifiedads/', include('classifiedad.api.urls', namespace='api_classifiedad')),
    path('api/chats/', include('chat.api.urls', namespace='api_chat')),
]

webapp/motando/motandoadm/urls.py
#
# motandoadm/urls.py
#

from django.urls import path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'motandoadm'

urlpatterns = [    
    path('home', login_required(views.HomeAdminView.as_view()), name='home'),  
    
    path('moto', login_required(views.ListAllMotorcycleAdminView.as_view()), name='motorcycle_all_list'),  

    path('moto/marca', login_required(views.ListMotorcycleBrandAdminView.as_view()), name='motorcycle_brand_list'),  
    path('moto/marca/novo', login_required(views.AddMotorcycleBrandAdminView.as_view()), name='motorcycle_brand_add'),  
    path('moto/marca/<int:brand_id>', login_required(views.EditMotorcycleBrandAdminView.as_view()), name='motorcycle_brand_edit'),  
    path('moto/marca/remover/<int:brand_id>', login_required(views.DeleteMotorcycleBrandAdminView.as_view()), name='motorcycle_brand_delete'),  

    path('moto/marca/modelo', login_required(views.SelectMotorcycleBrandModelAdminView.as_view()), name='motorcycle_brand_model_select'),  
    path('moto/marca/modelo/novo', login_required(views.AddMotorcycleBrandModelAdminView.as_view()), name='motorcycle_brand_model_add'),     
    path('moto/marca/<int:brand_id>/modelo', login_required(views.ListMotorcycleBrandModelAdminView.as_view()), name='motorcycle_brand_model_list'),  
    path('moto/marca/<int:brand_id>/modelo/<int:model_id>', login_required(views.EditMotorcycleBrandModelAdminView.as_view()), name='motorcycle_brand_model_edit'),  
    path('moto/marca/<int:brand_id>/modelo/<int:model_id>/remover', login_required(views.DeleteMotorcycleBrandModelAdminView.as_view()), name='motorcycle_brand_model_delete'),  

    path('moto/marca/modelo/versao', login_required(views.SelectMotorcycleBrandModelVersionAdminView.as_view()), name='motorcycle_brand_model_version_select'),  
    path('moto/marca/modelo/versao/novo', login_required(views.AddMotorcycleBrandModelVersionAdminView.as_view()), name='motorcycle_brand_model_version_add'),     
    path('moto/marca/<int:brand_id>/modelo/<int:model_id>/versao', login_required(views.ListMotorcycleBrandModelVersionAdminView.as_view()), name='motorcycle_brand_model_version_list'),      
    path('moto/marca/<int:brand_id>/modelo/<int:model_id>/versao/<int:version_id>', login_required(views.EditMotorcycleBrandModeVersionlAdminView.as_view()), name='motorcycle_brand_model_version_edit'),  
    path('moto/marca/modelo/versao/<int:version_id>/remover', login_required(views.DeleteMotorcycleBrandModelVersionAdminView.as_view()), name='motorcycle_brand_model_version_delete'),  

    #path('motorcycle/brand/<str:brand_id>/model/<int:model_id>/version/<int:version_id>', login_required(views.EditMotorcycleAdminView.as_view()), name='edit'),
]

webapp/motando/motandoadm/forms.py
#
# motandoadm/forms.py
#

from django import forms

from motorcycle.models import MotorcycleBrand, MotorcycleBrandModel, MotorcycleBrandModelVersion


class MotorcycleBrandForm(forms.ModelForm):    
    class Meta:
        model = MotorcycleBrand
        fields = ('brand',)
        labels = {'brand': 'Marca'}

        widgets = {
            'brand': forms.TextInput(attrs={'class': 'form-control'})
        }


class MotorcycleBrandModelForm(forms.ModelForm):        
    class Meta:
        model = MotorcycleBrandModel
        fields = ('brand', 'model',)
        labels = {'brand': 'Marca', 'model': 'Modelo'}

        widgets = {
            'brand': forms.Select(attrs={'class': 'form-control', 'readonly': True}),
            'model': forms.TextInput(attrs={'class': 'form-control'})
        }


class MotorcycleBrandModelVersionForm(forms.ModelForm):        
    class Meta:
        model = MotorcycleBrandModelVersion
        fields = ('model', 'version',)
        labels = {'model': 'Marca - Modelo', 'version': 'Versão'}

        widgets = {        
            'model': forms.Select(attrs={'class': 'form-control', 'readonly': True}),
            'version': forms.TextInput(attrs={'class': 'form-control'})
        }

webapp/motando/home/views.py
#
# home/views.py
#

from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View

from classifiedad.models import ClassifiedAd


class MainPageView(View):
    def get(self, request):
        max_top_classifiedad = 15

        top_classifiedad =  ClassifiedAd.objects.filter(status='published',
                                                        top_offer=True).all().order_by('-updated')[:max_top_classifiedad]

        return render(request, 'home.html', {
            'top_classifiedad': top_classifiedad
        })
    
    def post(self, request):
        search_url = request.POST.get('search_url', None)

        if search_url:            
            next_url = reverse('classifiedad:all') + '?q=' + search_url
        else:
            next_url = reverse('classifiedad:all')
        
        return redirect(next_url)
            

webapp/motando/motandoadm/views.py
#
# motandoadm/views.py
#

from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import Http404


from motorcycle.models import MotorcycleBrand, MotorcycleBrandModel, MotorcycleBrandModelVersion
from .forms import MotorcycleBrandForm, MotorcycleBrandModelForm, MotorcycleBrandModelVersionForm


class SuperUserRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    """Classe para verificar se o usuário é um super usuário."""
    def test_func(self):
        return self.request.user.is_superuser


class HomeAdminView(SuperUserRequiredMixin, View):
    def get(self, request):
        return render(request, 'motandoadm/home.html', {})        


class ListAllMotorcycleAdminView(SuperUserRequiredMixin, View):
    def get(self, request):
        return render(request, 'motandoadm/motorcycle_all.html', {}) 


class ListMotorcycleBrandAdminView(SuperUserRequiredMixin, View):
    def get(self, request):
        brand_list = MotorcycleBrand.objects.all()        
        paginator = Paginator(brand_list, 10)
                        
        page_number = request.GET.get('p')        
        brands_page = paginator.get_page(page_number)

        return render(request, 'motandoadm/motorcycle_brand_list.html', 
            {'brands_page': brands_page})
    

class AddMotorcycleBrandAdminView(SuperUserRequiredMixin, View):
    def get(self, request):
        form = MotorcycleBrandForm()

        return render(request, 'motandoadm/motorcycle_brand.html', {'form': form})
    
    def post(self, request):
        form = MotorcycleBrandForm(request.POST)

        if form.is_valid():
            form.save()

            messages.success(request, 'Moto Marca cadastrada com sucesso.')
        else:
            messages.error(request, 'Erro ao cadastrar Moto Marca.')
        
        return redirect('motandoadm:motorcycle_brand_list')


class EditMotorcycleBrandAdminView(SuperUserRequiredMixin, View):
    def get(self, request, brand_id: int):
        try:
            brand = MotorcycleBrand.objects.filter(id=brand_id).get()
        except MotorcycleBrand.DoesNotExist:
            raise Http404

        form = MotorcycleBrandForm(initial={'brand': brand.brand})

        return render(request, 'motandoadm/motorcycle_brand.html', 
            {'form': form, 'brand_id': brand_id})
    
    def post(self, request, brand_id: int):
        try:
            brand = MotorcycleBrand.objects.filter(id=brand_id).get()
        except MotorcycleBrand.DoesNotExist:
            raise Http404        

        form = MotorcycleBrandForm(request.POST, instance=brand)

        if form.is_valid():
            form.save()

            messages.success(request, 'Moto Marca atualizada com sucesso.')
        else:           
            messages.error(request, 'Erro ao atualizar Moto Marca.')
        
        return redirect('motandoadm:motorcycle_brand_list')


class DeleteMotorcycleBrandAdminView(SuperUserRequiredMixin, View):
    def get(self, request, brand_id: int):
        try:
            brand = MotorcycleBrand.objects.filter(id=brand_id).get()
        except MotorcycleBrand.DoesNotExist:
            raise Http404    
        
        return render(request, 'motandoadm/motorcycle_brand_delete.html', {'brand': brand})

    def post(self, request, brand_id: int):
        try:
            brand = MotorcycleBrand.objects.filter(id=brand_id).get()
        except MotorcycleBrand.DoesNotExist:
            raise Http404
                
        deleted = brand.delete()
      
        if deleted[0] == 1:
             messages.success(request, 'Moto Marca excluída com sucesso.')
        else:           
            messages.error(request, 'Erro ao excluir Moto Marca.')

        return redirect('motandoadm:motorcycle_brand_list')


class SelectMotorcycleBrandModelAdminView(SuperUserRequiredMixin, View):
    def get(self, request):       
        return render(request, 'motandoadm/motorcycle_brand_model_select.html', {})


class AddMotorcycleBrandModelAdminView(SuperUserRequiredMixin, View):
    def get(self, request):        
        form = MotorcycleBrandModelForm()

        return render(request, 'motandoadm/motorcycle_brand_model.html', 
            {'form': form})
    
    def post(self, request):
        form = MotorcycleBrandModelForm(data=request.POST)
        
        if form.is_valid():
            form.save()

            messages.success(request, 'Moto Modelo cadastrado com sucesso.')
        else:
            messages.error(request, 'Erro ao cadastrar Moto Moto Modelo.')
        
        return redirect('motandoadm:motorcycle_brand_model_add')
    

class ListMotorcycleBrandModelAdminView(SuperUserRequiredMixin, View):
    def get(self, request, brand_id: int):       
        try:
            motorcycle_model_list = MotorcycleBrandModel.objects.filter(brand__id=brand_id).all()
        except MotorcycleBrandModel.DoesNotExist:
            raise Http404
                     
        paginator = Paginator(motorcycle_model_list, 10)

        page_number = request.GET.get('p')        
        motorcycle_models_page = paginator.get_page(page_number)

        return render(request, 'motandoadm/motorcycle_brand_model_list.html', 
            {'brand_id': brand_id, 'motorcycle_models_page': motorcycle_models_page})


class EditMotorcycleBrandModelAdminView(SuperUserRequiredMixin, View):
    def get(self, request, brand_id: int, model_id: int):         
        motorcycle_model = get_object_or_404(MotorcycleBrandModel, id=model_id)
        
        form = MotorcycleBrandModelForm(instance=motorcycle_model)

        return render(request, 'motandoadm/motorcycle_brand_model.html', 
            {'form': form, 'brand_id': brand_id, 'model_id': model_id})
    
    def post(self, request, brand_id: int, model_id: int):
        motorcycle_model = get_object_or_404(MotorcycleBrandModel, id=model_id)
        
        form = MotorcycleBrandModelForm(request.POST, instance=motorcycle_model)
                                                          
        if form.is_valid():            
            form.save()            

            messages.success(request, 'Moto Marca Modelo atualizado com sucesso.')
        else:           
            messages.error(request, 'Erro ao atualizar Moto Marca Modelo.')
        
        return redirect('motandoadm:motorcycle_brand_model_list', brand_id=brand_id)


class DeleteMotorcycleBrandModelAdminView(SuperUserRequiredMixin, View):
    def get(self, request, brand_id: int, model_id: int): 
        motorcycle_model = get_object_or_404(MotorcycleBrandModel, id=model_id)

        return render(request, 'motandoadm/motorcycle_brand_model_delete.html', {'motorcycle_model': motorcycle_model})

    def post(self, request, brand_id: int, model_id: int): 
        motorcycle_model = get_object_or_404(MotorcycleBrandModel, id=model_id)

        deleted = motorcycle_model.delete()

        if deleted[0] == 1:
             messages.success(request, 'Moto Modelo excluído com sucesso.')
        else:           
            messages.error(request, 'Erro ao excluir Moto Modelo.')

        return redirect('motandoadm:motorcycle_brand_model_list', brand_id=brand_id)


class SelectMotorcycleBrandModelVersionAdminView(SuperUserRequiredMixin, View):
    def get(self, request):       
        return render(request, 'motandoadm/motorcycle_brand_model_version_select.html', {})


class AddMotorcycleBrandModelVersionAdminView(SuperUserRequiredMixin, View):
    pass


class ListMotorcycleBrandModelVersionAdminView(SuperUserRequiredMixin, View):
    def get(self, request, brand_id: int, model_id: int): 
        try:
            motorcycle_version_list = MotorcycleBrandModelVersion.objects.filter(model__brand__id=brand_id, 
                model__id=model_id).all()
        except MotorcycleBrandModelVersion.DoesNotExist:
            raise Http404
        
        paginator = Paginator(motorcycle_version_list, 10)

        page_number = request.GET.get('p')        
        motorcycle_versions_page = paginator.get_page(page_number)

        return render(request, 'motandoadm/motorcycle_brand_model_version_list.html', 
            {'motorcycle_versions_page': motorcycle_versions_page})


class EditMotorcycleBrandModeVersionlAdminView(SuperUserRequiredMixin, View):
    def get(self, request, brand_id: int, model_id: int, version_id: int):         
        motorcycle_version = get_object_or_404(MotorcycleBrandModelVersion, id=version_id)
        
        form = MotorcycleBrandModelVersionForm(instance=motorcycle_version)

        return render(request, 'motandoadm/motorcycle_brand_model_version.html', 
            {'form': form, 'brand_id': brand_id, 'model_id': model_id, 'version_id': version_id})

    def post(self, request, brand_id: int, model_id: int, version_id: int):  
        motorcycle_version = get_object_or_404(MotorcycleBrandModelVersion, id=version_id)
        
        form = MotorcycleBrandModelVersionForm(request.POST, instance=motorcycle_version)
                                                          
        print(form)

        if form.is_valid():            
            form.save()            

            messages.success(request, 'Moto Modelo Versão atualizado com sucesso.')
        else:           
            messages.error(request, 'Erro ao atualizar Moto Modelo Versão.')
        
        return redirect('motandoadm:motorcycle_brand_model_version_list', brand_id=brand_id, 
            model_id=model_id)


class DeleteMotorcycleBrandModelVersionAdminView(SuperUserRequiredMixin, View):
    def get(self, request, version_id: int):
        motorcycle_version = get_object_or_404(MotorcycleBrandModelVersion, id=version_id)       
        
        return render(request, 'motandoadm/motorcycle_brand_model_version_delete.html', 

webapp/motando/motandoadm/templates/motandoadm/motorcycle_brand_list.html
{% extends "motandoadm/include/base.html" %}
{% block title %} Moto (Marca) {% endblock %}
{% load static %}   
{% block head %}
   {{ block.super }}      
{% endblock %}
{% block body %}
   {% spaceless %} 
   {{ block.super }}
      
       <div class="container-fluid">           
          <h1 class="h1 mb-4 text-gray-800"> Moto </h1>
          <h4 class="h4 mb-4 text-gray-800"> Listar Marcas </h3>  
          <div class="row">
               <div class="col-12">
                   {% include "motandoadm/include/messages.html" %}      
               </div>
          </div>   
          <div class="row">
              <div class="col-6">
                  <div class="card shadow mb-4">
                     <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Listagem das Marcas de Moto cadastradas</h6>
                     </div>
                     <div class="card-body">
                        <div class="table-responsive">
                           <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                 <thead>
                                    <tr>
                                       <th>Marca</th>
                                       <th>Ação</th>                                       
                                    </tr>
                                 </thead>
                                 <tfoot>
                                    <tr>
                                       <th>Marca</th>
                                       <th>Ação</th>                                               
                                    </tr>
                                 </tfoot>
                                 <tbody>
                                    {% for brand in brands_page %}                                    
                                       <tr>
                                          <td> {{ brand }} </td>
                                          <td> 
                                             <a href="{% url 'motandoadm:motorcycle_brand_edit' brand_id=brand.id %}" class="text-decoration-none"> 
                                                <i class="fa fa-database" aria-hidden="true"></i> Editar 
                                             </a>
                                             &nbsp;&nbsp;
                                             <a href="{% url 'motandoadm:motorcycle_brand_delete' brand_id=brand.id %}" class="text-decoration-none"> 
                                                <i class="fa fa-trash" aria-hidden="true"></i> Excluír 
                                             </a>
                                          </td>
                                       </tr>
                                    {% endfor %}                                                            
                                 </tbody>
                           </table>
                        </div>
                     </div>
                  </div>
              </div>
          </div>    
          {% if brands_page.has_other_pages %}
                <div class="row">
                     <div class="col">
                         <nav aria-label="Moto Marcas Navegação">
                              <ul class="pagination">                                            
                                    {% if brands_page.has_previous %}
                                       <li class="page-item">
                                             <a class="page-link" href="?p={{ brands_page.previous_page_number }}">Anterior</a>
                                       </li>
                                    {% endif %}                                                
                                    {% for page_number in brands_page.paginator.page_range %}
                                       {% if brands_page.number  == page_number %}
                                             <li class="page-item active" aria-current="page">
                                                <span class="page-link"> {{ page_number }} </span>
                                             </li>                                                        
                                       {% else %}
                                             <li class="page-item">
                                                <a class="page-link" href="?p={{ page_number }}"> {{ page_number }} </a>
                                             </li>
                                       {% endif %}
                                    {% endfor %}                                                
                                    {% if brands_page.has_next %}
                                       <li class="page-item">
                                             <a class="page-link" href="?p={{ brands_page.next_page_number }}">Próximo</a>
                                       </li>
                                    {% endif %}
                              </ul>
                         </nav>
                     </div>
                </div>
          {% endif %}         
       </div>      
       <br><br> 
   {% endspaceless %} 
{% endblock %}
{% block footer %}
{% endblock %}
{% block body_scripts %}    
{% endblock %}

webapp/motando/motandoadm/templates/motandoadm/motorcycle_brand_model.html
{% extends "motandoadm/include/base.html" %}
{% block title %} Moto (Modelo) {% endblock %}
{% load static %}   
{% block head %}
   {{ block.super }}      
{% endblock %}
{% block body %}
   {% spaceless %} 
   {{ block.super }}      
       <div class="container-fluid">           
          <h1 class="h1 mb-4 text-gray-800"> Moto </h1>
          {% if brand_id and model_id %}
              <h4 class="h4 mb-4 text-gray-800"> Editar Modelo </h3>
              <form method="post" autocomplete="off" 
                    action="{% url 'motandoadm:motorcycle_brand_model_edit' brand_id=brand_id model_id=model_id %}">  
          {% else %}
              <h4 class="h4 mb-4 text-gray-800"> Adicionar Modelo </h3>
              <form method="post" autocomplete="off">    
          {% endif %}          
                {% csrf_token %}  
                <div class="row">
                    <div class="col-6">
                        {% include "motandoadm/include/messages.html" %}      
                    </div>
                </div>
                <div class="row">
                    <div class="col-3">
                        <div class="form-group">  
                            {{ form.as_p }}           
                            {% for form_errors in form.errors %}        
                                <p class="text-danger h6"> &#8226; {{ form_errors }} </p>       
                            {% endfor %}                            
                            {% if brand_id and model_id %}
                               <input type="hidden" name="brand_id" id="id_brand_id" value="{{ brand_id }}">
                               <input type="hidden" name="model_id" id="id_model_id" value="{{ model_id }}">
                            {% endif %}
                        </div>          
                    </div>
                </div>  
                <div class="row">
                    <div class="col-1">
                        {% if brand_id and model_id %}
                            <button type="submit" class="btn btn-info btn-block"> Atualizar </button>                            
                        {% else %}
                            <button type="submit" class="btn btn-success btn-block"> Salvar </button>
                        {% endif %}
                    </div>
                    <div class="col-1">
                        <a class="btn btn-secondary btn-block" 
                           href="{% url 'motandoadm:motorcycle_brand_model_select' %}" 
                           role="button"> Cancelar </a>
                    </div>
                </div> 
          </form>           
       </div>
       <br>
       <br>
   {% endspaceless %} 
{% endblock %}
{% block footer %}
{% endblock %}
{% block body_scripts %}       
{% endblock %}

webapp/motando/motandoadm/templates/motandoadm/motorcycle_brand_model_list.html
{% extends "motandoadm/include/base.html" %}
{% block title %} Moto (Modelo) {% endblock %}
{% load static %}   
{% block head %}
   {{ block.super }}      
{% endblock %}
{% block body %}
   {% spaceless %} 
   {{ block.super }}
      
       <div class="container-fluid">           
          <h1 class="h1 mb-4 text-gray-800"> Moto </h1>
          <h4 class="h4 mb-4 text-gray-800"> Listar Modelos </h3>  
          <div class="row">
               <div class="col-12">
                   {% include "motandoadm/include/messages.html" %}      
               </div>
          </div> 
          <div class="row">
            <div class="col-3">
                 <div class="form-group">
                     <label for="id_motorcycle_brand">Marca</label>
                     <select class="form-control" id="id_motorcycle_brand" disabled>                          
                     </select>
                 </div>                
            </div>
         </div>
         <div class="row">
            <div class="col-auto">
                <a class="btn btn-info btn-block" id="id_brand_model_list" onclick="listBrandModels();"> Listar Modelos </a>                   
            </div>
         </div> 
         <br> 
          <div class="row">
              <div class="col-6">
                  <div class="card shadow mb-4">
                     <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">Listagem dos Modelos das Marcas de Moto cadastradas</h6>
                     </div>
                     <div class="card-body">
                        <div class="table-responsive">
                           <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                 <thead>
                                    <tr>
                                       <th>Marca</th>
                                       <th>Modelo</th>
                                       <th>Ação</th>                                       
                                    </tr>
                                 </thead>
                                 <tfoot>
                                    <tr>
                                       <th>Marca</th>
                                       <th>Modelo</th>
                                       <th>Ação</th>                                               
                                    </tr>
                                 </tfoot>
                                 <tbody>
                                    {% for motorcycle_model in motorcycle_models_page %}                                    
                                       <tr>
                                          <td> {{ motorcycle_model.brand }} </td>
                                          <td> {{ motorcycle_model.model }} </td>
                                          <td> 
                                             <a href="{% url 'motandoadm:motorcycle_brand_model_edit' brand_id=motorcycle_model.brand.id model_id=motorcycle_model.id %}" 
                                                class="text-decoration-none"> 
                                                <i class="fa fa-database" aria-hidden="true"></i> Editar 
                                             </a>
                                             &nbsp;&nbsp;
                                             <a href="{% url 'motandoadm:motorcycle_brand_model_delete' brand_id=motorcycle_model.brand.id model_id=motorcycle_model.id %}" 
                                                class="text-decoration-none"> 
                                                <i class="fa fa-trash" aria-hidden="true"></i> Excluír 
                                             </a>
                                          </td>
                                       </tr>
                                    {% endfor %}                                                            
                                 </tbody>
                           </table>
                        </div>
                     </div>
                  </div>
              </div>
          </div>    
          {% if motorcycle_models_page.has_other_pages %}
                <div class="row">
                     <div class="col">
                         <nav aria-label="Moto Marcas Navegação">
                              <ul class="pagination">                                            
                                    {% if motorcycle_models_page.has_previous %}
                                       <li class="page-item">
                                             <a class="page-link" href="?p={{ motorcycle_models_page.previous_page_number }}">Anterior</a>
                                       </li>
                                    {% endif %}                                                
                                    {% for page_number in motorcycle_models_page.paginator.page_range %}
                                       {% if models_page.number  == page_number %}
                                             <li class="page-item active" aria-current="page">
                                                <span class="page-link"> {{ page_number }} </span>
                                             </li>                                                        
                                       {% else %}
                                             <li class="page-item">
                                                <a class="page-link" href="?p={{ page_number }}"> {{ page_number }} </a>
                                             </li>
                                       {% endif %}
                                    {% endfor %}                                                
                                    {% if motorcycle_models_page.has_next %}
                                       <li class="page-item">
                                             <a class="page-link" href="?p={{ motorcycle_models_page.next_page_number }}">Próximo</a>
                                       </li>
                                    {% endif %}
                              </ul>
                         </nav>
                     </div>
                </div>
          {% endif %}         
       </div>      
       <br><br> 
   {% endspaceless %} 
{% endblock %}
{% block footer %}
{% endblock %}
{% block body_scripts %}    
    <script type="text/javascript" src="{% static 'js/commons.js' %}"></script> 
    <script type="text/javascript">
         function listBrandModels() {            
             let brandId = $('#id_motorcycle_brand option:selected').val();
             let url = `/motandoadm/moto/marca/${brandId}/modelo`;

             $('#id_brand_model_list').attr('href', url).trigger('click');             
         }

         $(document).ready(function() {
               getMotorcycleBrand('id_motorcycle_brand', {{ brand_id }});                             
         });
    </script>
{% endblock %}